//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HwPassion.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DevRequirement
    {
        public int Id { get; set; }
        public string Require { get; set; }
        public string Description { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public string CreateUser { get; set; }
        public string Developor { get; set; }
        public Nullable<System.DateTime> StartDateTime { get; set; }
        public Nullable<System.DateTime> CompleteDateTime { get; set; }
        public int Status { get; set; }
    }
}
